name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: run deploy.sh # 步骤3
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN}}
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        run: npm install && npm run deploy
      
#       - name: DeployGitee
#         uses: okou19900722/gitee-pages@v1
#         with:
#           repository: 'https://gitee.com/cqnu-pc/cqnu-pc'
#           password: ${{ secrets.GITEE_TOKEN }}
#           branch: 'master'
#           directory: '/'
#           username: 'cqnu-pc'
#           # allow_empty_commit: true
#           # keep_files: true
#           # force_orphan: true
#           https: true
          
      # - name: Build Gitee Pages
      #   uses: yanglbme/gitee-pages-action@main
      #   with:
      #     # 注意替换为你的 Gitee 用户名
      #     gitee-username: cqnu-pc
      #     # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
      #     gitee-password: ${{ secrets.GITEE_TOKEN }}
      #     # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
      #     gitee-repo: cqnu-pc/cqnu-pc
      #     # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
      #     branch: master
